[[sarsop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ab23da424c55f367f36fd5fbb0fb30c075c3720"
os = "windows"

    [[sarsop.download]]
    sha256 = "96613be20b360a8126187dc2a160e32f2cd41296c6793e55ca00bbca590c646d"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.i686-w64-mingw32-cxx11.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37eca22d1389d3518c98411d4ba8e1a1c6f74980"
os = "windows"

    [[sarsop.download]]
    sha256 = "43e01bca0d455de0a4761bd65c07cad9988d94ced61116a75b73cfa7e730a1fc"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7923115b432994f0243e81445de85512a5a1347c"
os = "windows"

    [[sarsop.download]]
    sha256 = "36b357374fe92e6f1b043135fd46f5665c15c1d01424e5ff74010d4c7fd9cfce"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7be3cd201f9c3fbd8d6810e06bd28babfe7774c"
libc = "glibc"
os = "linux"

    [[sarsop.download]]
    sha256 = "feab360d9620ca4940de08010fe48c7a312e4f551c1646b4cbb58d43cee29b8b"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-linux-gnu-cxx11.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7603ec1aece6f17dfe13515bc4f481a1d6c7726"
os = "macos"

    [[sarsop.download]]
    sha256 = "ef0c9c3dd60e84d6dfe9e56e2dd25e601a6018a5b6247983bcaedb151e42cf52"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[sarsop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa6867b3772a8d0d3d99ec96ba005e6f3eadc24"
libc = "glibc"
os = "linux"

    [[sarsop.download]]
    sha256 = "7a5a72ca582524da7ce1717ca2655b83cac265a7dd6e8242b4bda1a970adc6fb"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.i686-linux-gnu-cxx11.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "781f10f41105568ce5a8bff3e74f9004572a31ee"
os = "macos"

    [[sarsop.download]]
    sha256 = "4141f2cbd0268dce943be22c2406b8acf2823e99346dfc136fe841a801b7b2be"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[sarsop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d45c44d68a0ad88110ded4e654980e77e1f2601"
os = "windows"

    [[sarsop.download]]
    sha256 = "bd97cb6037ba344c85ca7035b0f30d168c8fe8107e504f6c14774236e69d700b"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.i686-w64-mingw32-cxx03.tar.gz"
[[sarsop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23db7fac6c7e718ea6215cb77f81a06d7c1eb17d"
libc = "glibc"
os = "linux"

    [[sarsop.download]]
    sha256 = "8d92502cdee45c355880fe6a495682cdd7a9b3463947c8edd392dd2ec62b6462"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.x86_64-linux-gnu-cxx03.tar.gz"
[[sarsop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1d4210889af781c3e19ae9f6f746090a75e22ab"
libc = "glibc"
os = "linux"

    [[sarsop.download]]
    sha256 = "511a96dca70ded97e5e4585f0cf3651b098e96f4447517f3277f4b5a9a315d6c"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/sarsop-v0.96.0+0/sarsop.v0.96.0.i686-linux-gnu-cxx03.tar.gz"
