[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80254cd43abc6d73a93c91eda659a2af99a87b1"
os = "windows"

    [[SARSOP.download]]
    sha256 = "53eb44bf40f713b9b72b2a07b840d14d34f35c8564e12b0fb4605cbe827e55ca"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00ed266b9903de59f7344a2eb59b008cc823b9b5"
os = "windows"

    [[SARSOP.download]]
    sha256 = "8eb739bd9c1daafb0d1d8f1e588e5804c5b9a6fda1d32faf2deb01fe60fd6c65"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2c607bed123fdf91438b378a23dcbe31511c7cc"
os = "windows"

    [[SARSOP.download]]
    sha256 = "6360471e01bb9640c04c4a8f6a7bca3ba5e0f6027fbb1f5d38da1af7c3ac4ccc"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13b22994bc9d9a411103b1958863a44b3f370e69"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "8302b059d32b8b60cde0ad207a92e3aabc20b4cb07d98a6bc8f4c118cc0e3223"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "307e5263624b5ec9a80c72958f7382f666eadfe2"
os = "macos"

    [[SARSOP.download]]
    sha256 = "3236985577c03ab18ae9822ccd512a9a773f2f61176c00e02b0468f92f12a566"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bcc22838eb1885607c8a9b1a04230a76298a020"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "aab8cbe1079dfb235a994e5cef014d9699e2d9e5860bb0296dd0601e4c775f78"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9cd080473765fff695d108866864c569d7d3845"
os = "macos"

    [[SARSOP.download]]
    sha256 = "7fbf11d883066a40961ff90466e345bf01e0f18c967557b5fd955123a3af2a6d"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6802b86f20c6ba354819575024d3c98a3748078"
os = "windows"

    [[SARSOP.download]]
    sha256 = "8cc9d00204b36ddb284678030f17de17467776518853c28de9354e7c0cdb2f22"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx03.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fae4b7b918163e544bfeda2bc460f574fd4c732"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "cee30628d3cfe3a568ba8244a68186f7e56fe4e0aed3aa731e3518416fa75bdf"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "779e1a08567111f8f9442bb4dd6c2993772e46df"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "0c66cea1a35eb5c990db7e8acbaf4f114c1d7e54c970ea8b7237bbd6f4d3f0c4"
    url = "https://github.com/JuliaPOMDP/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx03.tar.gz"
